# JStudio Commander v1 — OSC 133 shell integration hook for zsh.
#
# Sourced per-session from ~/.jstudio-commander-v1/zdotdir/.zshrc, which is
# generated by the sidecar at startup. Does NOT modify user's ~/.zshrc.
#
# Spec citation: VSCode's shell-integration flavor of OSC 133 — same markers
# xterm.js addons and Warp/WezTerm parse. The sidecar parser
# (apps/sidecar/src/osc133/parser.ts) matches byte-exact \x1b]133;[ABCD]...\x07
# sequences per OS §24.1 (semantic-shape constraint documented at match site).
#
# Markers emitted:
#   \e]133;A\a        — prompt-start (emitted from precmd, after previous D)
#   \e]133;B\a        — command-start (emitted from preexec, right after Enter)
#   \e]133;D;<code>\a — command-finished (emitted from precmd, carries $?)
# The C marker ("command-executed boundary") is not emitted by this hook;
# B + D bracket the command execution, which is what the sidecar state machine
# consumes. C is reserved in the parser for future upstream tools that emit it.

# Idempotency guard — re-sourcing is a no-op.
[[ -n "${_JSTUDIO_OSC133_LOADED:-}" ]] && return 0
_JSTUDIO_OSC133_LOADED=1

_jstudio_osc133_precmd() {
    # Snapshot exit code BEFORE any other command (any subsequent command will
    # overwrite $?). Emit D for the command that just finished, then A for the
    # new prompt about to be drawn.
    local _jstudio_exit=$?
    printf '\e]133;D;%d\a' "$_jstudio_exit"
    printf '\e]133;A\a'
}

_jstudio_osc133_preexec() {
    # Fires after Enter is hit, before the command runs.
    printf '\e]133;B\a'
}

# Register hooks via zsh's add-zsh-hook utility. Guarded with && so a failure
# to load the autoload (extremely unlikely) doesn't break the shell.
autoload -U add-zsh-hook 2>/dev/null && {
    add-zsh-hook precmd  _jstudio_osc133_precmd
    add-zsh-hook preexec _jstudio_osc133_preexec
}
